# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feea856129527a3891505919aafe5bd3856c856285616c260f830a8ad88d75d4f172d6376cb90c038183a70ababed52b2326d5a47faefbaf8ef30cee82f24da8

test:
  secret_key_base: 676771bbb50f1bcc20bbd388bb410a841bed4cfbd0041af808f7aa269941d172707e92c9216f94c533bf7633a871cd879157e7b6c30b7b34a81f79a4233d0591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
